databases:
  - name: dominatus-db
    plan: free

services:
  - type: redis
    name: dominatus-redis
    plan: free
    ipAllowList:
      - ip: 0.0.0.0/0
        description: Allow all internal

  - type: web
    name: dominatus-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "dominatus.web.app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromService:
          type: database
          name: dominatus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: dominatus-redis
          property: connectionString
      - key: WEBAPP_URL
        fromService:
          type: web
          name: dominatus-web
          property: externalUrl

  - type: worker
    name: dominatus-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A dominatus.worker.tasks.celery_app worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromService:
          type: database
          name: dominatus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: dominatus-redis
          property: connectionString
